# Change these first
owner: casman300 # Your GitHub username
repo: my_website_upptimes # Your GitHub repository name

# Add your sites here
sites:
  - name: My Homepage
    url: https://casman.co.uk
  - name: Scouts Main Site
    url: https://12hs.org.uk
  - name: Baked Bean
    url: https://baked-bean.co.uk
  - name: 6xTask
    url: https://6xtask.co.uk
    icon: https://6xtask.co.uk/ASSETS/favicon/favicon.ico
  - name: Workshop Mayhem
    url: https://www.workshopmayhem.co.uk
    icon: https://www.workshopmayhem.co.uk/wp-content/uploads/2019/09/cropped-WM-Logo-180x180.png
    
assignees: # Users to assign downtime issues (optional)
  - casman300
  
status-website:
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /my_website_upptimes
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Charlie's Web Status
  introTitle: "Website Monitoring for websites by Charlie Seaman"
  introMessage: This is a colective status page for website I run or help to maintain. Including [my personal site](https://casman.co.uk), [1st &2nd Horley Scouts](https://12hs.org.uk), [Baked Bean](https://baked-bean.co.uk), [6xTASK](https://6xtask.co.uk) and [Workshop Mayhem](https://www.workshopmayhem.co.uk).
  navbar:
    - title: Status
      href: https://casman300.github.io/my_website_upptimes
    - title: My GitHub
      href: https://github.com/$OWNER/$REPO
     - title: My Site
      href: https://casman.co.uk

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
